test(libs/file-io/read-utils): expect error objects
- skills/_scripts/libs/file-io/__tests__/unit/read-utils.unit.spec.ts:
  throwFileIoError: false の説明と T-LIB-U-RF-08/09/11 の期待値を null から
  Error インスタンスに変更し、NotFound は ChatlogError の kind/subindex、
  PermissionDenied と NotADirectory は Error message を検証